### ISSUE TITLE
Identify method is missing

### ISSUE THREAD

**Issue by Kub-AT** [mixpanel/mixpanel-python#126]
> If using our Web/Mobile SDKs or a CDP like Segment or Rudderstack, there are only 2 steps:
> 
> Call .identify(<user_id>) when a user signs up or logs in. Pass in the user's known identifier (eg: their ID from your database).
> Call .reset() when a user logs out.

https://docs.mixpanel.com/docs/tracking-methods/identifying-users

**Comment by jaredmixpanel** [comment]
`mixpanel-python` is a server-side library, optimized for stateless shared usage; e.g., in a web application, the same mixpanel instance is used across requests for all users. Rather than setting a distinct_id through `identify()` calls like Mixpanel client-side libraries (where a single Mixpanel instance is tied to a single user), this library requires you to pass the `distinct_id` with every tracking call.
