### ISSUE TITLE
Validate https://api.mixpanel.com/ x509 certificate

### ISSUE THREAD

**Issue by graingert** [mixpanel/mixpanel-python#41]
This library uses urllib2 which on most versions of python does not validate x509 certificates.

Consider using the `requests` library?

**Comment by joeatwork** [comment]
This is a great suggestion!

In general, we want to introduce as few hard dependencies as we can, and that includes the HTTP library. That said, we've been bitten by shortcomings of system HTTP libraries a *lot*, and would like to make sure that people have the option of using better tools where they're available and appropriate.

A workaround for this issue until it's fixed would be to write your own consumer that uses `requests` rather than `urllib2`. We would be happy to accept pull requests that make this easier to do (and I'm filing another issue for it now, #42)

Internally, we should consider attempting to import requests, and only using urllib2 if requests can't be found.

**Comment by graingert** [comment]
I think this is worth changing so it will work with either requests
installed or python 2.7.9 so the code crashes rather than revealing the
api_key.

**Comment by krya** [comment]
+1.
on python 2.7.9 mixpanel crashes with famous exception in ssl

**Comment by seizethedave** [comment]
We now use urllib3 which validates certs by default.
