### ISSUE TITLE
Provide a way to send Super Properties

### ISSUE THREAD

**Issue by djds23** [mixpanel/mixpanel-python#44]
As far as I can tell from the documentation, it is only possible for one to send super properties from the javascript client. It would be fantastic to do this on the server side.

**Comment by joeatwork** [comment]
Super properties are just properties you send with every event, so you can quickly build this yourself- something like:

```py
class WithSupers(Mixpanel):
    def __init__(self, token, consumer=None):
        super(Mixpanel, self).__init__(token, consumer)
        self.super_properties = {}

    def track(self, distinct_id, event_name, properties=None, meta=None):
        if properties is None:
            properties = {}
        if meta is None:
            meta = {}

        all_properties = dict(self.super_properties, **properties)
        super(Mixpanel, self).track(distinct_id, event_name, all_properties, meta)
```

We don't provide them directly in the python library because it is often used in a server context, where the same object tracks multiple different users and circumstances at once- if you do take an approach like the above, you'll need to be sure that you don't register super properties for one user and then track on behalf of another user.

**Comment by djds23** [comment]
Thanks @joeatwork, great explanation. Feel free to close this issue.

**Comment by joeatwork** [comment]
Glad to help (and thanks for helping make the library better with your question!)
